FROM bcit/centos:7
# vim: syntax=dockerfile

LABEL maintainer="<%= maintainer %>"
LABEL version="<%= version %>"

ENV VERSION "<%= version %>"

COPY CentOS-OpenShift-Origin.repo /etc/yum.repos.d/
COPY CentOS-OpenShift-Origin311.repo /etc/yum.repos.d/

RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
    origin-clients-<%= version %>
